version: '3.8'
services:
  auth-service:
    build: ./auth-service
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - PORT=3001
    depends_on:
      - db
  booking-service:
    build: ./booking-service
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_SERVICE_URL=${ADMIN_SERVICE_URL}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - PORT=3002
    depends_on:
      - db
      - auth-service
      - booking-admin-service
  booking-admin-service:
    build: ./booking-admin-service
    ports:
      - "3003:3003"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - PORT=3003
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=pobeda_db_user
      - POSTGRES_PASSWORD=2ofNgztgwM6JIdzEJsopREWNfpvAkyXy
      - POSTGRES_DB=pobeda_db
    ports:
      - "5432:5432"
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init.sql